config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'users#index'
  resources :users
  resources :posts
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  body       :text(65535)
#  images     :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint
#
# Indexes
#
#  index_posts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Post < ApplicationRecord
  mount_uploaders :images, PostImageUploader
  serialize :images, JSON
  belongs_to :user
  validates :images, presence: true
  validates :body, presence: true, length: { maximum: 1000 }
end

app/models/user.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: users
#
#  id               :bigint           not null, primary key
#  crypted_password :string(255)
#  email            :string(255)      not null
#  salt             :string(255)
#  username         :string(255)      not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#


class User < ApplicationRecord
  authenticates_with_sorcery!
  validates :username, uniqueness: true, presence: true
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :email, uniqueness: true
  has_many :posts, dependent: :destroy

  def own?(object)
    id == object.user_id
  end

end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :danger

  def not_authenticated
    redirect_to login_path, warning: "ログインしてください"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, only: %i[new create edit update destroy]
  def index
    @posts = Post.all.includes(:user)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path, success: '投稿しました'
    else
      flash.now[:danger] = '投稿に失敗しました'
      render :new
    end
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    @post.update!(post_params)
    redirect_to posts_path, notice: "編集しました！"
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy!
    redirect_to posts_path, success: '投稿を削除しました'
  end

  def show
  end

  def post_params
    params.require(:post).permit(:body, images: [])
  end
end

app/controllers/user_sessions_controller.rb
# frozen_string_literal: true

class UserSessionsController < ApplicationController
  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to root_path, success: 'ログインしました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path, success: 'ログアウトしました'
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      auto_login(@user)
      redirect_to login_path, success: 'ユーザーを作成しました'
    else
      flash.now[:danger] = 'ユーザーの作成に失敗しました'
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :username)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/user_sessions_helper.rb
# frozen_string_literal: true

module UserSessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | MyInstaClone
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    body
      - if logged_in?
        = render 'shared/header'
      - else
        = render 'shared/before_login_header'
      = render 'shared/flash_messages'
      main
      = yield

app/views/posts/_post.html.slim
.card.mb-5.post
  .card-header
    .d-flex.align-items-center
      - if logged_in? && current_user.own?(post)
        = link_to edit_post_path(post) do
          = icon 'far', 'edit', class: 'fa-lg'
      - if logged_in? && current_user.own?(post)
        = link_to post_path(post), method: :delete do
          = icon 'far', 'trash-alt', class: 'fa-lg'
      = image_tag 'profile-placeholder.png', size: '40x40', class: 'rounded-circle mr-1'
      = post.user.username
      - if current_user&.own?(post)
        .ml-auto
          = link_to post_path(post), class: 'mr-3', method: :delete, data: {confirm: '本当に削除しますか？'} do
            = icon 'far', 'trash-alt', class: 'fa-lg'
          = link_to edit_post_path(post) do
            = icon 'far', 'edit', class: 'fa-lg'
  = link_to post_path(post) do
    .swiper-container
      .swiper-wrapper
        - post.images.each do |image|
          .swiper-slide
            = image_tag image.url, class: 'card-img-top'
      .swiper-pagination
  .card-body
    .card-text
      = post.body

app/views/posts/create.html.slim
h1 Posts#create
p Find me in app/views/posts/create.html.slim

app/views/posts/destroy.html.slim
h1 Posts#destroy
p Find me in app/views/posts/destroy.html.slim

app/views/posts/edit.html.slim
= form_with model: @post, local: true do |f|
  = f.label :images
  = f.file_field :images, multiple: true, accept: 'image/*'
  = f.label :body
  = f.text_area :body
  = f.submit

app/views/posts/index.html.slim
= render @posts

app/views/posts/new.html.slim
= form_with model: @post, local: true do |f|
  = f.label :images
  = f.file_field :images, multiple: true, accept: 'image/*'
  = f.label :body
  = f.text_area :body
  = f.submit

app/views/posts/show.html.slim
.post-detail.card
  .image-box
    .swiper-container
      .swiper-wrapper
        - @post.images.each do |image|
          .swiper-slide
            = image_tag image.url
      .swiper-pagination
  .image-info-box
    .profile-box.p-3
      .d-flex.align-items-center
        = image_tag 'profile-placeholder.png', size: '40x40', class: 'rounded-circle mr-1'
        = @post.user.username
        - if current_user&.own?(@post)
          .ml-auto
            = link_to post_path(@post), class: 'mr-3', method: :delete, data: {confirm: '本当に削除しますか？'} do
              = icon 'far', 'trash-alt', class: 'fa-lg'
            = link_to edit_post_path(@post) do
              = icon 'far', 'edit', class: 'fa-lg'
    hr.m-0
    .post-body.p-3
      / 投稿の本文
      .row.no-gutters
        .col-2
          = image_tag 'profile-placeholder.png', size: '40x40', class: 'rounded-circle'
        .col-10
          = simple_format(@post.body)
      hr
      / コメント一覧
      .row.no-gutters
        .col-2
          = image_tag 'profile-placeholder.png', size: '40x40', class: 'rounded-circle'
        .col-10
          | ダミーコメントダミーコメントダミーコメント
      hr
      .row.no-gutters
        .col-2
          = image_tag 'profile-placeholder.png', size: '40x40', class: 'rounded-circle'
        .col-10
          | ダミーコメントダミーコメントダミーコメント
    hr.m-0
    .post-comment.p-3
      form.form-inline.mb-0
        input type="text" class="form-control input-comment-body" placeholder="コメント"
        button type="submit" class="btn btn-primary btn-raised"
          | 投稿

app/views/posts/update.html.slim
h1 Posts#update
p Find me in app/views/posts/update.html.slim

app/views/shared/_before_login_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-white
  = link_to 'InstaClone', root_path, class: 'navbar-brand'
  button.navbar-toggler aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarTogglerDemo02" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  #navbarTogglerDemo02.collapse.navbar-collapse
    form.form-inline.my-2.my-lg-0.mr-auto
      input.form-control.mr-sm-2 placeholder="Search" type="search" /
      button.btn.btn-outline-success.my-2.my-sm-0 type="submit"  Search
    ul.navbar-nav.mt-2.mt-lg-0
      li.nav-item
        = link_to 'ポスト一覧', '#', class: 'nav-link'
      li.nav-item
        = link_to 'ログイン', login_path, class: 'nav-link'

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_messages.alert.alert-danger
    ul.mb-0
      - object.errors.full_messages.each do |msg|
        li = msg

app/views/shared/_flash_messages.html.slim
- flash.each do |message_type, message|
  div class=("alert alert-#{message_type}") = message

app/views/shared/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-white
  = link_to 'InstaClone', root_path, class: 'navbar-brand'
  button.navbar-toggler aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarTogglerDemo02" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  #navbarTogglerDemo02.collapse.navbar-collapse
    form.form-inline.my-2.my-lg-0.mr-auto
      input.form-control.mr-sm-2 placeholder="Search" type="search" /
      button.btn.btn-outline-success.my-2.my-sm-0 type="submit"  Search
    ul.navbar-nav.mt-2.mt-lg-0
      li.nav-item
        a.nav-link href="#"
          = icon 'far', 'image', class: 'fa-lg'
      li.nav-item
        a.nav-link href="#"
          = icon 'far', 'heart', class: 'fa-lg'
      li.nav-item
        a.nav-link href="#"
          = icon 'far', 'user', class: 'fa-lg'
      li.nav-item
        = link_to 'ログアウト', logout_path, class: 'nav-link', method: :delete

app/views/user_sessions/create.html.slim
h1 UserSessions#create
p Find me in app/views/user_sessions/create.html.slim

app/views/user_sessions/destroy.html.slim
h1 UserSessions#destroy
p Find me in app/views/user_sessions/destroy.html.slim

app/views/user_sessions/new.html.slim
.login-register-form
  .login-register-form-inner
    .card.mb-3
      = form_with url: login_path, class: 'card-body', local: true do |f|
        .form-group
          = f.label :email, 'メールアドレス', class: 'bmd-label-floating'
          = f.email_field :email, class: 'form-control'
        .form-group
          = f.label :password, 'パスワード', class: 'bmd-label-floating'
          = f.password_field :password, class: 'form-control'
        = f.submit 'ログイン', class: 'btn btn-raised btn-primary'
    .card
      .card-body
        | アカウントをお持ちでないですか？
        = link_to '登録する', new_user_path

app/views/users/new.html.slim
.login-register-form
  .login-register-form-inner
    .card.mb-3
      = form_with model: @user, class: 'card-body', local: true do |f|
        = render 'shared/error_messages', object: @user
        .form-group
          = f.label :username, class: 'bmd-label-floating'
          = f.text_field :username, class: 'form-control'
        .form-group
          = f.label :email, class: 'bmd-label-floating'
          = f.email_field :email, class: 'form-control'
        .form-group
          = f.label :password, class: 'bmd-label-floating'
          = f.password_field :password, class: 'form-control'
        .form-group
          = f.label :password_confirmation, class: 'bmd-label-floating'
          = f.password_field :password_confirmation, class: 'form-control'
        = f.submit '登録', class: 'btn btn-raised btn-primary'
    .card
      .card-body
        | アカウントをお持ちですか
        = link_to 'ログインする', login_path